configuration:  
  projectName: bungalows-service
#Bungalows Service Port
server:
 port: 8084
   
logging:
 file: MaslBungalows.log
 level: INFO
 
# MongoDB Properties 
spring:
 data:
  mongodb:
   dbuser: masluser
   database: MahaweliDB
   password: g+H1ppDyrXldSwoLBo6c6Q==
   host: 192.168.12.106
   uri: mongodb://dofuser:Mzw4#12@192.168.12.137:27017,192.168.12.138:27017,192.168.12.136:27017/ForestDB?replicaSet=dof
   port: 27017
   maxConnectionsPerHost: 10000
   threadsAllowedToBlockForConnectionMultiplier: 5
   serverSelectionTimeout: 30000
   maxWaitTime: 120000
   connectTimeout: 10000
   socketTimeout: 0
   socketKeepAlive: false
   sslEnabled: false
   sslInvalidHostNameAllowed: false
   alwaysUseMBeans: false 
   heartbeatFrequency: 10000
   minHeartbeatFrequency: 500
   heartbeatConnectTimeout: 20000
   heartbeatSocketTimeout: 20000
   localThreshold: 15
   cursorFinalizerEnabled: true
   
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.12.135:8761/eureka/,http://192.168.12.136:8761/eureka/
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false

